import { emailAddress } from '../../src/patterns/email-address'
import { testPattern } from '../utils/test-pattern'

testPattern({
	name: 'emailAddress',
	pattern: emailAddress,
	validCases: [
		'foo@bar.com',
		'x@x.au',
		'foo@bar.com.au',
		'foo+bar@bar.com',
		'test123+ext@gmail.com',
		'some.name.midd.leNa.me.and.locality+extension@GoogleMail.com',
		'"foobar"@example.com',
		'"  foo  m端ller "@example.com',
		'"foo\\@bar"@example.com',
		`${'a'.repeat(64)}@${'a'.repeat(63)}.com`,
		`${'a'.repeat(64)}@${'a'.repeat(63)}.com`,
		`${'a'.repeat(31)}@gmail.com`,
		'test@gmail.com',
		'test.1@gmail.com',
		'test@1337.com',
	],
	invalidCases: [
		'invalidemail@',
		'invalid.com',
		'@invalid.com',
		'foo@bar.com.',
		'somename@ｇｍａｉｌ.com',
		'foo@bar.co.uk.',
		'z@co.c',
		'hans.m端ller@test.com',
		'test|123@m端ller.com',
		'ｇｍａｉｌｇｍａｉｌｇｍａｉｌｇｍａｉｌｇｍａｉｌ@gmail.com',
		// local part too long
		// `${'a'.repeat(65)}@${'a'.repeat(63)}.com`,
		// dns label too long
		`${'a'.repeat(64)}@${'a'.repeat(64)}.com`,
		// domain name too long
		// `${'a'.repeat(64)}@${'a'.repeat(63)}.${'a'.repeat(63)}.${'a'.repeat(
		// 	63,
		// )}.${'a'.repeat(60)}.com`,
		'test1@invalid.co m',
		'test2@invalid.co m',
		'test3@invalid.co m',
		'test4@invalid.co m',
		'test5@invalid.co m',
		'test6@invalid.co m',
		'test7@invalid.co m',
		'test8@invalid.co m',
		'test9@invalid.co m',
		'test10@invalid.co m',
		'test11@invalid.co m',
		'test12@invalid.co　m',
		'test13@invalid.co　m',
		'multiple..dots@stillinvalid.com',
		'test123+invalid! sub_address@gmail.com',
		'gmail...ignores...dots...@gmail.com',
		'ends.with.dot.@gmail.com',
		'multiple..dots@gmail.com',
		'wrong()[]",:;<>@@gmail.com',
		'"wrong()[]",:;<>@@gmail.com',
		'username@domain.com�',
		'username@domain.com©',
	],
})
